import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { HeaderNav } from "@/components/header-nav";
import { cn } from "@/lib/utils"

// const inter = Inter({ subsets: ["latin"]});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-mono flex flex-col h-screen">
        <HeaderNav />
        <main className="bg-slate-700 flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
